#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Jun 17, 2018 12:10:38 AM

import sys
import os

try:
    from Tkinter import *
    from Tkinter.filedialog import askopenfilename
except ImportError:
    from tkinter import *
    from tkinter.filedialog import askopenfilename

import requests
try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import trans_ui_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    trans_ui_support.set_Tk_var()
    top = New_Toplevel (root)
    trans_ui_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    trans_ui_support.set_Tk_var()
    top = New_Toplevel (w)
    trans_ui_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel():
    global w
    w.destroy()
    w = None


class New_Toplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        
        self.filename = ""
        self.pathname = ""
        self.fileextension = ""
        self.pathEntry = StringVar()
        self.filenameEntry = StringVar()
        self.fileextensionEntry = StringVar()
        self.filetPathSuccess = StringVar()

        top.geometry("600x242+555+141")
        top.title("Lingua franca")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Browse = Button(top)
        self.Browse.place(relx=0.03, rely=0.08, height=24, width=87)
        self.Browse.configure(activebackground="#d9d9d9")
        self.Browse.configure(activeforeground="#000000")
        self.Browse.configure(background="#d9d9d9")
        self.Browse.configure(command=self.onBrowse)
        self.Browse.configure(disabledforeground="#a3a3a3")
        self.Browse.configure(foreground="#000000")
        self.Browse.configure(highlightbackground="#d9d9d9")
        self.Browse.configure(highlightcolor="black")
        self.Browse.configure(pady="0")
        self.Browse.configure(text='''Browse''')

        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.02, rely=0.29, relheight=0.64, relwidth=0.53)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(width=315)

        self.PathEntry = Entry(self.Frame1)
        self.PathEntry.place(relx=0.29, rely=0.36,height=20, relwidth=0.65)
        self.PathEntry.configure(background="white")
        self.PathEntry.configure(disabledforeground="#a3a3a3")
        self.PathEntry.configure(font="TkFixedFont")
        self.PathEntry.configure(foreground="#000000")
        self.PathEntry.configure(insertbackground="black")
        self.PathEntry.configure(textvariable=self.pathEntry)
        self.PathEntry.configure(width=204)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.02, rely=0.34, height=21, width=64)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Path :''')
        self.Label1.configure(width=64)

        self.Label2 = Label(self.Frame1)
        self.Label2.place(relx=0.06, rely=0.11, height=21, width=54)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Filename :''')

        self.Entry2 = Entry(self.Frame1)
        self.Entry2.place(relx=0.29, rely=0.13,height=20, relwidth=0.65)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(textvariable=self.filenameEntry)
        self.Entry2.configure(width=204)

        self.Label3 = Label(self.Frame1)
        self.Label3.place(relx=0.05, rely=0.59, height=21, width=74)
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''Extension :''')
        self.Label3.configure(width=74)

        self.Entry3 = Entry(self.Frame1)
        self.Entry3.place(relx=0.29, rely=0.59,height=20, relwidth=0.65)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(textvariable=self.fileextensionEntry)
        self.Entry3.configure(width=204)

        self.Frame2 = Frame(top)
        self.Frame2.place(relx=0.57, rely=0.29, relheight=0.64, relwidth=0.39)
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(background="#d9d9d9")
        self.Frame2.configure(width=235)

        self.Label4 = Label(self.Frame2)
        self.Label4.place(relx=0.06, rely=0.14, height=21, width=40)
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''From :''')

        self.Label5 = Label(self.Frame2)
        self.Label5.place(relx=0.09, rely=0.38, height=21, width=23)
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(text='''To :''')

        self.Entry4 = Entry(self.Frame2)
        self.Entry4.place(relx=0.26, rely=0.14,height=20, relwidth=0.7)
        self.Entry4.configure(background="white")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="TkFixedFont")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(insertbackground="black")
        self.Entry4.configure(textvariable=trans_ui_support.From)

        self.Entry5 = Entry(self.Frame2)
        self.Entry5.place(relx=0.26, rely=0.38,height=20, relwidth=0.7)
        self.Entry5.configure(background="white")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font="TkFixedFont")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(insertbackground="black")
        self.Entry5.configure(textvariable=trans_ui_support.To)

        self.Translate = Button(self.Frame2)
        self.Translate.place(relx=0.49, rely=0.66, height=24, width=107)
        self.Translate.configure(activebackground="#d9d9d9")
        self.Translate.configure(activeforeground="#000000")
        self.Translate.configure(background="#d9d9d9")
        self.Translate.configure(command=self.translate)
        self.Translate.configure(disabledforeground="#a3a3a3")
        self.Translate.configure(foreground="#000000")
        self.Translate.configure(highlightbackground="#d9d9d9")
        self.Translate.configure(highlightcolor="black")
        self.Translate.configure(pady="0")
        self.Translate.configure(text='''Translate''')
        self.Translate.configure(width=107)

        self.Label6 = Label(top)
        self.Label6.place(relx=0.20, rely=0.08, height=24, width=30)
        self.Label6.configure(background="#d9d9d9")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(text='''Path :''')
        self.Label6.configure(width=64)

        self.Entry6 = Entry(top)
        self.Entry6.place(relx=0.25 , rely=0.09, height=20, relwidth=0.5)
        self.Entry6.configure(background="white")
        self.Entry6.configure(disabledforeground="#a3a3a3")
        self.Entry6.configure(font="TkFixedFont")
        self.Entry6.configure(foreground="#000000")
        self.Entry6.configure(insertbackground="black")
        self.Entry6.configure(textvariable=self.filetPathSuccess)

        self.Open = Button(top)
        self.Open.place(relx=0.80, rely=0.08, height=24, width=87)
        self.Open.configure(activebackground="#d9d9d9")
        self.Open.configure(activeforeground="#000000")
        self.Open.configure(background="#d9d9d9")
        self.Open.configure(command=self.openfile)
        self.Open.configure(disabledforeground="#a3a3a3")
        self.Open.configure(foreground="#000000")
        self.Open.configure(highlightbackground="#d9d9d9")
        self.Open.configure(highlightcolor="black")
        self.Open.configure(pady="0")
        self.Open.configure(text='''Open''')

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#f9f9f9")
        Popupmenu1.configure(activeborderwidth="1")
        Popupmenu1.configure(activeforeground="black")
        Popupmenu1.configure(background="#d9d9d9")
        Popupmenu1.configure(borderwidth="1")
        Popupmenu1.configure(disabledforeground="#a3a3a3")
        Popupmenu1.configure(font="{Segoe UI} 9")
        Popupmenu1.configure(foreground="black")
        Popupmenu1.post(event.x_root, event.y_root)

    def onBrowse(self):
        self.filename = askopenfilename( filetypes = ( ("files","*.txt"), ("files", "*.*") ))
        fileSplit = self.filename.split("/")
        filename = fileSplit[len(fileSplit)-1].split('.')
        self.pathEntry.set(self.filename)
        self.filenameEntry.set(filename[0])
        self.fileextensionEntry.set(filename[1])

    def translate(self):
        f = open(self.filename, "r", encoding='utf-8')
        if f.mode == 'r':
            contents = f.read()
            f.close()
            r = requests.post("http://localhost:8000/translate", data={ "message": contents })
            self.newFilename = self.filename.split('.')[0] + "_en." + self.filename.split(".")[1];

            rfile = open(self.newFilename, "w+", encoding='utf-8')
            rfile.write(r.json()['text'])
            rfile.close()
            self.filetPathSuccess.set(self.newFilename)    

    def openfile(self):
        os.startfile(self.newFilename)


if __name__ == '__main__':
    vp_start_gui()



